// ==========================================
// REPORTS.JS - REPORTS MANAGEMENT LOGIC
// ==========================================

let reports = [];

/**
 * Load Reports Page
 */
async function loadReportsPage() {
    try {
        const response = await fetch('pages/reports.html');
        const html = await response.text();
        document.getElementById('reportsPage').innerHTML = html;

        setTimeout(() => {
            // Setup event listeners
            const reportForm = document.getElementById('reportFormElement');
            if (reportForm) {
                reportForm.addEventListener('submit', handleReportFormSubmit);
            }

            // Load hostels for dropdown
            loadHostelsForReports();
            loadReports();
        }, 100);
    } catch (error) {
        console.error('Error loading reports page:', error);
        showError('Failed to load reports page');
    }
}

/**
 * Load Hostels for Report Form
 */
async function loadHostelsForReports() {
    try {
        const response = await api.getAllHostels();
        if (response.success) {
            const select = document.getElementById('reportHostel');
            if (select) {
                const options = response.data.map(hostel =>
                    `<option value="${hostel._id}">${escapeHtml(hostel.hostelName)}</option>`
                ).join('');
                select.innerHTML = '<option value="">Select a hostel</option>' + options;
            }
        }
    } catch (error) {
        console.error('Error loading hostels:', error);
    }
}

/**
 * Load Reports
 */
async function loadReports() {
    try {
        const response = await api.getAllReports();

        if (response.success) {
            reports = response.data;
            displayReports(reports);
        }
    } catch (error) {
        console.error('Error loading reports:', error);
        showError('Failed to load reports');
    }
}

/**
 * Display Reports
 */
function displayReports(reportList) {
    const reportsList = document.getElementById('reportsList');
    const noReports = document.getElementById('noReports');

    if (!reportsList) return;

    if (reportList.length === 0) {
        reportsList.innerHTML = '';
        show('noReports');
        return;
    }

    hide('noReports');
    reportsList.innerHTML = reportList.map(report => `
        <div class="report-card">
            <div class="report-card-header">
                <div>
                    <h3>${escapeHtml(report.title)}</h3>
                    <span class="report-type">${report.reportType.toUpperCase()}</span>
                </div>
                <button class="btn btn-danger btn-sm" onclick="deleteReportConfirm('${report._id}')">Delete</button>
            </div>
            <div class="report-card-content">
                ${report.description ? `<p>${escapeHtml(report.description)}</p>` : ''}
                <p><strong>Generated By:</strong> ${escapeHtml(report.generatedBy?.name || 'Unknown')}</p>
                <p><strong>Generated On:</strong> ${new Date(report.createdAt).toLocaleString()}</p>
                ${report.hostelId ? `<p><strong>Hostel:</strong> ${escapeHtml(report.hostelId.hostelName || 'N/A')}</p>` : ''}
            </div>
        </div>
    `).join('');
}

/**
 * Load Report Form
 */
function loadReportForm() {
    const form = document.getElementById('reportForm');
    if (form) {
        document.getElementById('reportFormElement').reset();
        show('reportForm');
    }
}

/**
 * Cancel Report Form
 */
function cancelReportForm() {
    hide('reportForm');
    document.getElementById('reportFormElement').reset();
}

/**
 * Handle Report Form Submit
 */
async function handleReportFormSubmit(event) {
    event.preventDefault();

    const formData = {
        reportType: document.getElementById('reportType').value,
        title: document.getElementById('reportTitle').value,
        description: document.getElementById('reportDescription').value,
        hostelId: document.getElementById('reportHostel').value || undefined,
        data: {},
    };

    if (!formData.reportType || !formData.title) {
        showError('Please fill required fields', 'reportFormError');
        return;
    }

    try {
        const response = await api.createReport(formData);

        if (response.success) {
            showToast('Report generated successfully!', 'success');
            cancelReportForm();
            loadReports();
        }
    } catch (error) {
        showError(error.message || 'Failed to generate report', 'reportFormError');
    }
}

/**
 * Delete Report Confirmation
 */
function deleteReportConfirm(reportId) {
    if (confirm('Are you sure you want to delete this report? This action cannot be undone.')) {
        deleteReport(reportId);
    }
}

/**
 * Delete Report
 */
async function deleteReport(reportId) {
    try {
        const response = await api.deleteReport(reportId);

        if (response.success) {
            showToast('Report deleted successfully!', 'success');
            loadReports();
        }
    } catch (error) {
        showError(error.message || 'Failed to delete report');
    }
}
